---

# (c) Wong Hoi Sing Edison <hswong3i@pantarei-design.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: include default variables
  include_vars: "../vars/main.yml"

- name: include release specific variables
  include_vars: "{{ _loop_var }}"
  loop: "{{ query('first_found', _params) }}"
  loop_control:
    loop_var: _loop_var
  vars:
    _params:
      files:
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version | lower }}.yml"
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
        - "{{ ansible_distribution | lower }}.yml"
        - "{{ ansible_os_family | lower }}-{{ ansible_distribution_version | lower }}.yml"
        - "{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
        - "{{ ansible_os_family | lower }}.yml"
      paths:
        - "../vars"
      skip: true

- name: include release specific tasks
  include_tasks: "{{ _loop_var }}"
  loop: "{{ query('first_found', _params) }}"
  loop_control:
    loop_var: _loop_var
  vars:
    _params:
      files:
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version | lower }}.yml"
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
        - "{{ ansible_distribution | lower }}.yml"
        - "{{ ansible_os_family | lower }}-{{ ansible_distribution_version | lower }}.yml"
        - "{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
        - "{{ ansible_os_family | lower }}.yml"
      paths:
        - "."
      skip: true

- name: prepare directories
  file:
    dest: "{{ item.dest }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0755') }}"
    state: "{{ item.state | default('directory') }}"
  loop:
    - { dest: "/etc/ceph" }
    - { dest: "/lib/systemd/system" }
    - { dest: "/lib/systemd/system/ceph-mon.target.d" }
    - { dest: "/var/lib/ceph/bootstrap-mds", owner: "ceph", group: "ceph" }
    - { dest: "/var/lib/ceph/bootstrap-mgr", owner: "ceph", group: "ceph" }
    - { dest: "/var/lib/ceph/bootstrap-osd", owner: "ceph", group: "ceph" }
    - { dest: "/var/lib/ceph/bootstrap-rgw", owner: "ceph", group: "ceph" }
    - { dest: "/var/lib/ceph/mon", owner: "ceph", group: "ceph" }
    - { dest: "/var/lib/ceph/tmp", owner: "ceph", group: "ceph" }

- name: touch files
  copy:
    dest: "{{ item.dest }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0644') }}"
    content: ""
    force: false
  loop:
    - { dest: "/etc/ceph/ceph.conf", owner: "ceph", group: "ceph" }

- name: tweak settings in ini files
  ini_file:
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    state: "{{ item.state }}"
    path: "/etc/ceph/ceph.conf"
    mode: "0644"
  loop: "{{ ceph_mon_config }}"
  notify:
    - ceph_mon | systemctl restart ceph-mon.target

- name: prepare files
  file:
    dest: "{{ item.dest }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0644') }}"
    state: "{{ item.state | default('file') }}"
  loop:
    - { dest: "/etc/ceph/ceph.conf", owner: "ceph", group: "ceph" }
  notify:
    - ceph_mon | systemctl restart ceph-mon.target

- name: create monitor initial keyring
  shell: |
    set -euxo pipefail
    ceph-authtool \
      --gen-key \
      --name mon. \
      --cap mon 'allow *' \
      --create-keyring /var/lib/ceph/tmp/ceph.mon.keyring
    chown ceph:ceph /var/lib/ceph/tmp/ceph.mon.keyring
    chmod 0600 /var/lib/ceph/tmp/ceph.mon.keyring
  args:
    executable: "/bin/bash"
    creates: "/var/lib/ceph/tmp/ceph.mon.keyring"
  when: inventory_hostname == ansible_play_hosts[0]
  delegate_to: "{{ ansible_play_hosts[0] }}"
  register: result
  changed_when: result is not succeeded
  notify:
    - ceph_mon | systemctl restart ceph-mon.target

- name: create and import admin keyring
  shell: |
    set -euxo pipefail
    ceph-authtool \
      --gen-key \
      --name client.admin \
      --cap mon 'allow *' \
      --cap mgr 'allow *' \
      --cap osd 'allow *' \
      --cap mds 'allow *' \
      --create-keyring /etc/ceph/ceph.client.admin.keyring
    chown ceph:ceph /etc/ceph/ceph.client.admin.keyring
    chmod 0600 /etc/ceph/ceph.client.admin.keyring
    ceph-authtool /var/lib/ceph/tmp/ceph.mon.keyring \
      --import-keyring /etc/ceph/ceph.client.admin.keyring
  args:
    executable: "/bin/bash"
    creates: "/etc/ceph/ceph.client.admin.keyring"
  when: inventory_hostname == ansible_play_hosts[0]
  delegate_to: "{{ ansible_play_hosts[0] }}"
  register: result
  changed_when: result is not succeeded
  notify:
    - ceph_mon | systemctl restart ceph-mon.target

- name: base64 encode
  shell: |
    set -euxo pipefail
    tar zcfP - {{ _params | join(' ') }} | base64 -w 0
  vars:
    _params:
      - "/etc/ceph/ceph.client.admin.keyring"
      - "/var/lib/ceph/tmp/ceph.mon.keyring"
  args:
    executable: "/bin/bash"
  when: inventory_hostname != ansible_play_hosts[0]
  delegate_to: "{{ ansible_play_hosts[0] }}"
  register: base64_encode_result
  changed_when: base64_encode_result is not succeeded

- name: base64 decode
  shell: |
    set -euxo pipefail
    echo -n {{ base64_encode_result.stdout | quote }} | base64 -d | tar zx -C /
  args:
    executable: "/bin/bash"
  when: inventory_hostname != ansible_play_hosts[0]
  register: base64_decode_result
  changed_when: base64_decode_result is not succeeded

- name: prepare files
  file:
    dest: "{{ item.dest }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0644') }}"
    state: "{{ item.state | default('file') }}"
  loop:
    - { dest: "/etc/ceph/ceph.client.admin.keyring", owner: "ceph", group: "ceph", mode: "0600" }
    - { dest: "/var/lib/ceph/tmp/ceph.mon.keyring", owner: "ceph", group: "ceph", mode: "0600" }
  notify:
    - ceph_mon | systemctl restart ceph-mon.target

- name: tweak settings in ini files
  ini_file:
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    state: "{{ item.state }}"
    path: "/lib/systemd/system/ceph-mon@.service"
    no_extra_spaces: true
    mode: "0644"
  loop:
    - { state: "present", section: "Service", option: "ProtectClock", value: "false" }
    - { state: "present", section: "Service", option: "ProtectHostname", value: "false" }
    - { state: "present", section: "Service", option: "ProtectKernelLogs", value: "false" }
    - { state: "present", section: "Service", option: "RestrictSUIDSGID", value: "false" }
  notify:
    - ceph_mon | systemctl daemon-reload
    - ceph_mon | systemctl restart ceph-mon.target

- name: ceph monitor mkfs with keyring
  shell: |
    set -euxo pipefail
    mkdir -p /var/lib/ceph/mon/ceph-{{ inventory_hostname }}
    chown ceph:ceph /var/lib/ceph/mon/ceph-{{ inventory_hostname }}
    chmod 0755 /var/lib/ceph/mon/ceph-{{ inventory_hostname }}
    ceph-mon \
      --mkfs \
      --id {{ inventory_hostname }} \
      --cluster ceph \
      --setuser ceph \
      --setgroup ceph \
      --keyring /var/lib/ceph/tmp/ceph.mon.keyring
    chown ceph:ceph /var/lib/ceph/mon/ceph-{{ inventory_hostname }}/keyring
    chmod 0600 /var/lib/ceph/mon/ceph-{{ inventory_hostname }}/keyring
  args:
    executable: "/bin/bash"
    creates: "/var/lib/ceph/mon/ceph-{{ inventory_hostname }}/keyring"
  register: result
  changed_when: result is not succeeded
  notify:
    - ceph_mon | systemctl restart ceph-mon.target

- name: prepare files
  file:
    dest: "{{ item.dest }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0644') }}"
    state: "{{ item.state | default('file') }}"
  loop:
    - { dest: "/lib/systemd/system/ceph-mon.target" }
    - { dest: "/lib/systemd/system/ceph-mon@.service" }
    - { dest: "/var/lib/ceph/mon/ceph-{{ inventory_hostname }}/keyring", owner: "ceph", group: "ceph", mode: "0600" }
  notify:
    - ceph_mon | systemctl daemon-reload
    - ceph_mon | systemctl restart ceph-mon.target

- name: flush handlers
  meta: flush_handlers

- name: "systemctl start ceph-mon@{{ inventory_hostname }}.service"
  shell: |
    set -euxo pipefail
    systemctl enable ceph-mon@{{ inventory_hostname }}.service
    systemctl start ceph-mon@{{ inventory_hostname }}.service
  args:
    executable: "/bin/bash"
  changed_when: false
  failed_when: false

- name: systemctl start ceph-mon.target
  service:
    name: "ceph-mon.target"
    state: "started"
    enabled: true
  changed_when: false
  failed_when: false

- name: ceph auth get client.bootstrap-*
  shell: |
    set -euxo pipefail
    ceph \
      auth get client.{{ item.client }} \
      --out-file /var/lib/ceph/{{ item.client }}/ceph.keyring
    chown ceph:ceph /var/lib/ceph/{{ item.client }}/ceph.keyring
    chmod 0600 /var/lib/ceph/{{ item.client }}/ceph.keyring
  args:
    executable: "/bin/bash"
    creates: "/var/lib/ceph/{{ item.client }}/ceph.keyring"
  loop:
    - { client: "bootstrap-mgr" }
    - { client: "bootstrap-osd" }
    - { client: "bootstrap-mds" }
    - { client: "bootstrap-rgw" }
  loop_control:
    label: { dest: "/var/lib/ceph/{{ item.client }}/ceph.keyring" }
  register: result
  until: result is succeeded
  changed_when: result is not succeeded

- name: prepare files
  file:
    dest: "{{ item.dest }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0644') }}"
    state: "{{ item.state | default('file') }}"
  loop:
    - { dest: "/var/lib/ceph/bootstrap-mds/ceph.keyring", owner: "ceph", group: "ceph", mode: "0600" }
    - { dest: "/var/lib/ceph/bootstrap-mgr/ceph.keyring", owner: "ceph", group: "ceph", mode: "0600" }
    - { dest: "/var/lib/ceph/bootstrap-osd/ceph.keyring", owner: "ceph", group: "ceph", mode: "0600" }
    - { dest: "/var/lib/ceph/bootstrap-rgw/ceph.keyring", owner: "ceph", group: "ceph", mode: "0600" }
